import org.hidetake.gradle.swagger.generator.GenerateSwaggerUI

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.epages.restdocs-api-spec' version '0.18.2'
    id 'org.hidetake.swagger.generator' version '2.18.2'
}

group = 'org.sopt'
version = '0.0.1-SNAPSHOT'

openapi3 {
    servers = [
            { url = "https://api.confeti.xyz" },
            { url = "http://localhost:8080" }
    ]
    title = "CONFETI Server API Document"
    description = "-"
    version = "0.0.1"
    format = "yaml"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

swaggerSources {
    sample {
        setInputFile(file("${project.buildDir}/api-spec/openapi3.yaml"))
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // psy
//    implementation 'p6spy:p6spy:3.9.1'
//    implementation 'com.github.gavlyukovskiy:datasource-decorator-spring-boot-autoconfigure:1.9.0'

    // Thymeleaf
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // AWS S3
    implementation 'io.awspring.cloud:spring-cloud-aws-starter:3.1.1'
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-s3:3.1.1'

    // actuator
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // DB
    runtimeOnly 'com.mysql:mysql-connector-j'

    // JWT
    implementation group: 'io.jsonwebtoken', name: 'jjwt-api', version: '0.12.6'
    runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-impl', version: '0.12.6'
    runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-jackson', version: '0.12.6'

    // Web Client
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'io.netty:netty-resolver-dns-native-macos:4.1.68.Final:osx-aarch_64'

    // HTTP Client
    implementation 'org.apache.httpcomponents.client5:httpclient5'

    // AOP
    implementation 'org.springframework.boot:spring-boot-starter-aop'

    // Elastic Search
    implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'

    // Komoran
    implementation 'com.github.shin285:KOMORAN:3.3.9'

    // Bouncy Castle
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Redis
    implementation "org.springframework.boot:spring-boot-starter-data-redis"

    // Jackson
    implementation "com.fasterxml.jackson.core:jackson-databind"
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

    // Spring Rest Docs
    testImplementation "com.epages:restdocs-api-spec-restassured:0.18.2"
    testImplementation 'org.springframework.restdocs:spring-restdocs-restassured'
    testImplementation 'io.rest-assured:rest-assured'
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
    testImplementation 'com.epages:restdocs-api-spec-mockmvc:0.18.2'

    // Test Containers
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:elasticsearch'
    testImplementation 'org.testcontainers:mysql'

    // Swagger
    swaggerUI 'org.webjars:swagger-ui:4.11.1'
}

dependencyManagement {
    imports {
        mavenBom "org.testcontainers:testcontainers-bom:1.17.4"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(GenerateSwaggerUI) {
    dependsOn 'openapi3'

    doFirst {
        def swaggerUIFile = file("${openapi3.outputDirectory}/openapi3.yml")

        def securitySchemesContent = "  securitySchemes:\n" +         \
                                             "    bearerAuth:\n" +         \
                                             "      type: https\n" +         \
                                             "      scheme: bearer\n" +         \
                                             "      bearerFormat: JWT\n" +         \
                                             "      name: Authorization\n" +         \
                                             "      in: header\n" +        \
                                             "      description: \"Use 'your-access-token' as the value of the Authorization header\"\n" +        \
                                             "security:\n" +
                "  - bearerAuth: []  # Apply the security scheme here"

        swaggerUIFile.append securitySchemesContent
    }
}

// 생성된 Swagger UI 파일들 복사
tasks.register('copySwaggerDocument', Copy) {
    dependsOn generateSwaggerUISample

    from file("build/swagger-ui-sample/")
    into file("src/main/resources/static/docs")
}

// 생성된 OpenAPI 파일 복사
tasks.register('copyOpenAPIDocument', Copy) {
    dependsOn generateSwaggerUISample

    from file("build/api-spec/")
    into file("src/main/resources/static/docs")
}

bootJar {
    dependsOn copySwaggerDocument, copyOpenAPIDocument
}
