spring:
  config:
    import:
      - aws-secretsmanager:/confeti-api/prod/elastic-search?prefix=es-secrets.

  data:
    elasticsearch:
      uris: ${es-secrets.host}:${es-secrets.port}
      username: ${es-secrets.username}
      password: ${es-secrets.password}
